### ISSUE TITLE
USER STORY: User feedback in poll

### ISSUE THREAD

**Issue by HasibullahFathi** [HasibullahFathi/life-hacks#3]
as a **user** i can **choose to hide my identity in the poll response** so that i can **provide anonymous feedback**

## Acceptance criteria:
* This icon should be provided as a checkbox
* The checkbox should be checked by default
* The option should appear next to the submit button
* after submitting the default submission confirmation should be adjusted to include the username

## Tasks: 
- [x] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the username of the submitter
- [ ] Create a new field in to the model to track the username
- [ ] Update the controller function 
- [ ] Update unit test script
- [ ] Test the functionality
